site_name: Test the docs
nav:
    - Home: index.md
    - Random notes:
        - Bash: bash.md
        - slurm: index.md
theme:
  name: readthedocs
  highlightjs: true


# site_name: Test the docs
# theme:
#   name: readthedocs
#   highlightjs: true
# plugins:
#   - search
#   - mkdocstrings:
#       handlers:
#         # See: https://mkdocstrings.github.io/python/usage/
#         python:
#           options:
#             docstring_style: sphinx
# markdown_extensions:
#   - markdown_include.include:
#       base_path: .
#   - admonition


